package msfsmodmanager.ui.edit;

import java.awt.Color;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.ToolTipManager;
import msfsmodmanager.logic.ErrorHandler;

import msfsmodmanager.model.Mod;
import msfsmodmanager.model.ModType;
import msfsmodmanager.model.Continent;
import msfsmodmanager.model.AircraftType;
import msfsmodmanager.util.SwingUtil;
import msfsmodmanager.state.ModsDb;

import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/*
 * Note: We would like to use toolTipText for error messages / background color for error highlighting,
 * but none of these work with editable ComboBoxes if Look&Feel is "Nimbus". Therefore:
 * we use separate labels for error messages / a separate label component for error highlighting.
 */
public class EditModsFrame extends javax.swing.JFrame {
    public static final Color CHECK_ERROR_COLOR = new Color(255,51,51);
    
    EditModsFrameHandler handler;
    
    private ColoredListCellRenderer coloredListCellRenderer;

    /**
     * Creates new form EditModsFrame
     */
    public EditModsFrame(List<Mod> mods) {
        handler = new EditModsFrameHandler(this, mods);
        coloredListCellRenderer = new ColoredListCellRenderer(handler);
        
        initComponents();
        
        /*
         * Note: These need to happen *before* setting the item for the first time.
         * Otherwise, this first "set item" operation will be ignored and
         * simply the first item from the list will become the default selection.
         */
        AutoCompleteDecorator.decorate(authorComboBox);
        AutoCompleteDecorator.decorate(cityComboBox);
        
        handler.initFrame();
        SwingUtil.initPanel(this, modsList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editPanel = new javax.swing.JPanel();
        editTopPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        urlPanel = new javax.swing.JPanel();
        urlErrorLabel = new WarnLightLabel(handler, "url")
        ;
        jPanel1Msgs = new MessagePanel("url");
        urlMsgLabel = new MessageLabel(handler, "url", "Must start with " + Mod.FLIGHTSIM_TO_URL_WITH_WWW_START)
        ;
        jPanel2 = new javax.swing.JPanel();
        descriptionPanel = new javax.swing.JPanel();
        descriptionErrorLabel = new WarnLightLabel(handler, "description");
        authorPanel = new javax.swing.JPanel();
        authorErrorLabel = new WarnLightLabel(handler, "author");
        jPanel2Msgs = new MessagePanel("description", "author");
        descriptionMsgLabel = new MessageLabel(handler, "description");
        authorMsgLabel = new MessageLabel(handler, "author");
        jPanel3 = new javax.swing.JPanel();
        typePanel = new javax.swing.JPanel();
        typeErrorLabel = new WarnLightLabel(handler, "type");
        jPanel3Msgs = new MessagePanel("type");
        typeMsgLabel = new MessageLabel(handler, "type");
        jPanel4 = new javax.swing.JPanel();
        countryPanel = new javax.swing.JPanel();
        countryErrorLabel = new WarnLightLabel(handler, "country");
        continentPanel = new javax.swing.JPanel();
        continentErrorLabel = new WarnLightLabel(handler, "continent");
        jPanel4Msgs = new MessagePanel("country", "continent");
        countryMsgLabel = new MessageLabel(handler, "country");
        continentMsgLabel = new MessageLabel(handler, "continent");
        cityErrorLabel = new WarnLightLabel(handler, "city");
        icaoErrorLabel = new WarnLightLabel(handler, "icao");
        aircraftTypeErrorLabel = new WarnLightLabel(handler, "aircraftType");
        jPanel5Msgs = new MessagePanel("city", "icao", "aircraftType");
        cityMsgLabel = new MessageLabel(handler, "city");
        icaoMsgLabel = new MessageLabel(handler, "icao");
        aircraftTypeMsgLabel = new MessageLabel(handler, "aircraftType");
        listPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modsList = new JList(handler.modNames);
        titleLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        buttonPanelWest = new javax.swing.JPanel();
        updateModDbButton = new javax.swing.JButton();
        buttonPanelEast = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add mods");
        getContentPane().setLayout(new java.awt.BorderLayout(4, 0));

        editPanel.setLayout(new java.awt.BorderLayout());

        editTopPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Properties"));
        editTopPanel.setLayout(new javax.swing.BoxLayout(editTopPanel, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        urlPanel.setLayout(new java.awt.BorderLayout());

        urlErrorLabel.setText("  ");
        urlErrorLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        urlErrorLabel.setOpaque(true);
        urlPanel.add(urlErrorLabel, java.awt.BorderLayout.WEST);
        urlPanel.add(urlTextField, java.awt.BorderLayout.CENTER);

        jPanel1.add(urlPanel);

        editTopPanel.add(jPanel1);

        jPanel1Msgs.setLayout(new java.awt.GridLayout(1, 0));

        urlMsgLabel.setText("jLabel1");
        jPanel1Msgs.add(urlMsgLabel);

        editTopPanel.add(jPanel1Msgs);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 8, 0));

        descriptionPanel.setLayout(new java.awt.BorderLayout());

        descriptionErrorLabel.setText("  ");
        descriptionErrorLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        descriptionErrorLabel.setOpaque(true);
        descriptionPanel.add(descriptionErrorLabel, java.awt.BorderLayout.WEST);

        descriptionTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        descriptionPanel.add(descriptionTextField, java.awt.BorderLayout.CENTER);

        jPanel2.add(descriptionPanel);

        authorPanel.setLayout(new java.awt.BorderLayout());

        authorErrorLabel.setText("  ");
        authorErrorLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        authorErrorLabel.setOpaque(true);
        authorPanel.add(authorErrorLabel, java.awt.BorderLayout.WEST);

        authorComboBox.setEditable(true);
        authorPanel.add(authorComboBox, java.awt.BorderLayout.CENTER);

        jPanel2.add(authorPanel);

        editTopPanel.add(jPanel2);

        jPanel2Msgs.setLayout(new java.awt.GridLayout(1, 0));

        descriptionMsgLabel.setText("jLabel2");
        jPanel2Msgs.add(descriptionMsgLabel);

        authorMsgLabel.setText("jLabel3");
        jPanel2Msgs.add(authorMsgLabel);

        editTopPanel.add(jPanel2Msgs);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        typePanel.setLayout(new java.awt.BorderLayout());

        typeErrorLabel.setText("  ");
        typeErrorLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        typeErrorLabel.setOpaque(true);
        typePanel.add(typeErrorLabel, java.awt.BorderLayout.WEST);

        typeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeComboBoxItemStateChanged(evt);
            }
        });
        typePanel.add(typeComboBox, java.awt.BorderLayout.CENTER);

        jPanel3.add(typePanel);

        editTopPanel.add(jPanel3);

        jPanel3Msgs.setLayout(new java.awt.GridLayout(1, 0));

        typeMsgLabel.setText("jLabel4");
        jPanel3Msgs.add(typeMsgLabel);

        editTopPanel.add(jPanel3Msgs);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 8, 0));

        countryPanel.setLayout(new java.awt.BorderLayout());

        countryErrorLabel.setText("  ");
        countryErrorLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        countryErrorLabel.setOpaque(true);
        countryPanel.add(countryErrorLabel, java.awt.BorderLayout.WEST);

        countryComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                countryComboBoxItemStateChanged(evt);
            }
        });
        countryPanel.add(countryComboBox, java.awt.BorderLayout.CENTER);

        jPanel4.add(countryPanel);

        continentPanel.setLayout(new java.awt.BorderLayout());

        continentErrorLabel.setText("  ");
        continentErrorLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        continentErrorLabel.setOpaque(true);
        continentPanel.add(continentErrorLabel, java.awt.BorderLayout.WEST);

        continentComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                continentComboBoxItemStateChanged(evt);
            }
        });
        continentPanel.add(continentComboBox, java.awt.BorderLayout.CENTER);

        jPanel4.add(continentPanel);

        editTopPanel.add(jPanel4);

        jPanel4Msgs.setLayout(new java.awt.GridLayout(1, 0));

        countryMsgLabel.setText("jLabel5");
        jPanel4Msgs.add(countryMsgLabel);

        continentMsgLabel.setText("jLabel6");
        jPanel4Msgs.add(continentMsgLabel);

        editTopPanel.add(jPanel4Msgs);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        cityPanel.setLayout(new java.awt.BorderLayout());

        cityErrorLabel.setText("  ");
        cityErrorLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cityErrorLabel.setOpaque(true);
        cityPanel.add(cityErrorLabel, java.awt.BorderLayout.WEST);

        cityComboBox.setEditable(true);
        cityPanel.add(cityComboBox, java.awt.BorderLayout.CENTER);

        jPanel5.add(cityPanel);

        icaoPanel.setLayout(new java.awt.BorderLayout());

        icaoErrorLabel.setText("  ");
        icaoErrorLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        icaoErrorLabel.setOpaque(true);
        icaoPanel.add(icaoErrorLabel, java.awt.BorderLayout.WEST);
        icaoPanel.add(icaoTextField, java.awt.BorderLayout.CENTER);

        jPanel5.add(icaoPanel);

        aircraftTypePanel.setLayout(new java.awt.BorderLayout());

        aircraftTypeErrorLabel.setText("  ");
        aircraftTypeErrorLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        aircraftTypeErrorLabel.setOpaque(true);
        aircraftTypePanel.add(aircraftTypeErrorLabel, java.awt.BorderLayout.WEST);
        aircraftTypePanel.add(aircraftTypeComboBox, java.awt.BorderLayout.CENTER);

        jPanel5.add(aircraftTypePanel);

        editTopPanel.add(jPanel5);

        jPanel5Msgs.setLayout(new java.awt.GridLayout(1, 0));

        cityMsgLabel.setText("jLabel7");
        jPanel5Msgs.add(cityMsgLabel);

        icaoMsgLabel.setText("jLabel8");
        jPanel5Msgs.add(icaoMsgLabel);

        aircraftTypeMsgLabel.setText("jLabel9");
        jPanel5Msgs.add(aircraftTypeMsgLabel);

        editTopPanel.add(jPanel5Msgs);

        editPanel.add(editTopPanel, java.awt.BorderLayout.NORTH);

        getContentPane().add(editPanel, java.awt.BorderLayout.CENTER);

        listPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Mods"));
        listPanel.setLayout(new java.awt.BorderLayout());

        modsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        modsList.setSelectedIndex(0);
        modsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                modsListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(modsList);
        modsList.setCellRenderer(coloredListCellRenderer);

        listPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(listPanel, java.awt.BorderLayout.WEST);

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        titleLabel.setText("Found the following unregistered mods. Please add them to your mods registry.");
        titleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 8, 4));
        getContentPane().add(titleLabel, java.awt.BorderLayout.NORTH);

        buttonPanel.setLayout(new java.awt.BorderLayout());

        buttonPanelWest.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        updateModDbButton.setText("Search for new mod definitions online (Update mod DB)");
        updateModDbButton.setToolTipText(ModsDb.instance.isUpdatable() ? null : "Can be updated every 10 minutes only.");
        updateModDbButton.setEnabled(ModsDb.instance.isUpdatable());
        updateModDbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateModDbButtonActionPerformed(evt);
            }
        });
        buttonPanelWest.add(updateModDbButton);

        buttonPanel.add(buttonPanelWest, java.awt.BorderLayout.WEST);

        buttonPanelEast.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        okButton.setText("Add all");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        buttonPanelEast.add(okButton);

        buttonPanel.add(buttonPanelEast, java.awt.BorderLayout.EAST);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        handler.save();
        handler.addAll();
    }//GEN-LAST:event_okButtonActionPerformed

    private void modsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_modsListValueChanged
        handler.changesModSelection = true;
        handler.save();
        handler.setMod(modsList.getSelectedValue());
        handler.updateMessagePanels();
        handler.changesModSelection = false;
        revalidate();
        repaint();
    }//GEN-LAST:event_modsListValueChanged

    private void countryComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_countryComboBoxItemStateChanged
        handler.changeCountry();
    }//GEN-LAST:event_countryComboBoxItemStateChanged

    private void typeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeComboBoxItemStateChanged
        handler.changeType();
    }//GEN-LAST:event_typeComboBoxItemStateChanged

    private void continentComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_continentComboBoxItemStateChanged
        handler.changeContinent();
    }//GEN-LAST:event_continentComboBoxItemStateChanged

    private void updateModDbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateModDbButtonActionPerformed
        handler.updateModsDb();
    }//GEN-LAST:event_updateModDbButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void show(List<Mod> mods) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditModsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditModsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditModsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditModsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditModsFrame(mods).setVisible(true);
            }
        });
    }

    public ExampleComboBox<AircraftType> getAircraftTypeComboBox() {
        return (ExampleComboBox<AircraftType>) aircraftTypeComboBox;
    }

    public ExampleComboBox<String> getAuthorComboBox() {
        return (ExampleComboBox<String>) authorComboBox;
    }

    public ExampleComboBox<String> getCityComboBox() {
        return (ExampleComboBox<String>) cityComboBox;
    }

    public ExampleComboBox<Continent> getContinentComboBox() {
        return (ExampleComboBox<Continent>) continentComboBox;
    }

    public ExampleComboBox<String> getCountryComboBox() {
        return (ExampleComboBox<String>) countryComboBox;
    }

    public ExampleComboBox<ModType> getTypeComboBox() {
        return (ExampleComboBox<ModType>) typeComboBox;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JComboBox<AircraftType> aircraftTypeComboBox = new ExampleComboBox("(Choose aircraft type)");
    private javax.swing.JLabel aircraftTypeErrorLabel;
    public javax.swing.JLabel aircraftTypeMsgLabel;
    public final javax.swing.JPanel aircraftTypePanel = new javax.swing.JPanel();
    private final javax.swing.JComboBox<String> authorComboBox = new ExampleComboBox("(Choose or enter author)");
    private javax.swing.JLabel authorErrorLabel;
    private javax.swing.JLabel authorMsgLabel;
    private javax.swing.JPanel authorPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel buttonPanelEast;
    private javax.swing.JPanel buttonPanelWest;
    private final javax.swing.JComboBox<String> cityComboBox = new ExampleComboBox("(Choose or enter city)");
    private javax.swing.JLabel cityErrorLabel;
    public javax.swing.JLabel cityMsgLabel;
    public final javax.swing.JPanel cityPanel = new javax.swing.JPanel();
    private final javax.swing.JComboBox<Continent> continentComboBox = new ExampleComboBox<Continent>("(Choose continent)");
    private javax.swing.JLabel continentErrorLabel;
    private javax.swing.JLabel continentMsgLabel;
    private javax.swing.JPanel continentPanel;
    private final javax.swing.JComboBox<String> countryComboBox = new ExampleComboBox("(Choose country)");
    private javax.swing.JLabel countryErrorLabel;
    private javax.swing.JLabel countryMsgLabel;
    private javax.swing.JPanel countryPanel;
    private javax.swing.JLabel descriptionErrorLabel;
    private javax.swing.JLabel descriptionMsgLabel;
    private javax.swing.JPanel descriptionPanel;
    public final javax.swing.JTextField descriptionTextField = new ExampleTextField("Mod title");
    private javax.swing.JPanel editPanel;
    public javax.swing.JPanel editTopPanel;
    private javax.swing.JLabel icaoErrorLabel;
    public javax.swing.JLabel icaoMsgLabel;
    public final javax.swing.JPanel icaoPanel = new javax.swing.JPanel();
    public final javax.swing.JTextField icaoTextField = new ExampleTextField("ICAO");
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel1Msgs;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel2Msgs;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel3Msgs;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel4Msgs;
    public final javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
    public javax.swing.JPanel jPanel5Msgs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listPanel;
    private javax.swing.JList<String> modsList;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel titleLabel;
    private final javax.swing.JComboBox<ModType> typeComboBox = new ExampleComboBox("(Choose mod type)");
    private javax.swing.JLabel typeErrorLabel;
    private javax.swing.JLabel typeMsgLabel;
    private javax.swing.JPanel typePanel;
    private javax.swing.JButton updateModDbButton;
    private javax.swing.JLabel urlErrorLabel;
    private javax.swing.JLabel urlMsgLabel;
    private javax.swing.JPanel urlPanel;
    public final javax.swing.JTextField urlTextField = new ExampleTextField("https://www.flightsim.to/file/1/example-mod");
    // End of variables declaration//GEN-END:variables
}
