package msfsmodmanager.ui;

import java.util.Arrays;
import java.util.List;
import msfsmodmanager.model.Continent;

public class MainFrame extends javax.swing.JFrame {
    public final ContinentPanel eu = new ContinentPanel(Continent.EU);
    public final ContinentPanel us = new ContinentPanel(Continent.US);
    public final ContinentPanel na = new ContinentPanel(Continent.NA);
    public final ContinentPanel sa = new ContinentPanel(Continent.SA);
    public final ContinentPanel as = new ContinentPanel(Continent.AS);
    public final ContinentPanel af = new ContinentPanel(Continent.AF);
    public final ContinentPanel oz = new ContinentPanel(Continent.OZ);
    public final ContinentPanel aa = new ContinentPanel(Continent.AA);
    
    private final MainFrameHandler handler = new MainFrameHandler(this);

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typePanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        applyButton = new javax.swing.JButton();
        mainScrollPane = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        continentsPanel1 = new javax.swing.JPanel();
        continentsPanel1.add(eu);
        continentsPanel2 = new javax.swing.JPanel();
        continentsPanel2.add(us);
        continentsPanel2.add(na);
        continentsPanel2.add(sa);
        continentsPanel3 = new javax.swing.JPanel();
        continentsPanel3.add(as);
        continentsPanel3.add(af);
        continentsPanel4 = new javax.swing.JPanel();
        continentsPanel4.add(oz);
        continentsPanel4.add(aa);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MSFS Mod Selector");

        airportCheckBox.setSelected(true);
        airportCheckBox.setText("Airports");
        typePanel.add(airportCheckBox);

        landmarkCheckBox.setSelected(true);
        landmarkCheckBox.setText("Landmarks");
        typePanel.add(landmarkCheckBox);

        cityCheckBox.setText("Cities");
        typePanel.add(cityCheckBox);

        landscapeCheckBox.setText("Landscapes");
        typePanel.add(landscapeCheckBox);

        landscapeFixCheckBox.setSelected(true);
        landscapeFixCheckBox.setText("Landscape fixes");
        typePanel.add(landscapeFixCheckBox);

        livreryCheckBox.setSelected(true);
        livreryCheckBox.setText("Livreries");
        typePanel.add(livreryCheckBox);

        getContentPane().add(typePanel, java.awt.BorderLayout.NORTH);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setText("Deactivate all");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        buttonPanel.add(jButton1);

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(applyButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        mainPanel.setLayout(new java.awt.GridLayout(1, 5));

        continentsPanel1.setLayout(new javax.swing.BoxLayout(continentsPanel1, javax.swing.BoxLayout.PAGE_AXIS));
        mainPanel.add(continentsPanel1);

        continentsPanel2.setLayout(new javax.swing.BoxLayout(continentsPanel2, javax.swing.BoxLayout.PAGE_AXIS));
        mainPanel.add(continentsPanel2);

        continentsPanel3.setLayout(new javax.swing.BoxLayout(continentsPanel3, javax.swing.BoxLayout.PAGE_AXIS));
        mainPanel.add(continentsPanel3);

        continentsPanel4.setLayout(new javax.swing.BoxLayout(continentsPanel4, javax.swing.BoxLayout.PAGE_AXIS));
        mainPanel.add(continentsPanel4);

        mainScrollPane.setViewportView(mainPanel);

        getContentPane().add(mainScrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        handler.apply();
    }//GEN-LAST:event_applyButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        handler.deactivateAll();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public final javax.swing.JCheckBox airportCheckBox = new javax.swing.JCheckBox();
    private javax.swing.JButton applyButton;
    private javax.swing.JPanel buttonPanel;
    public final javax.swing.JCheckBox cityCheckBox = new javax.swing.JCheckBox();
    private javax.swing.JPanel continentsPanel1;
    private javax.swing.JPanel continentsPanel2;
    private javax.swing.JPanel continentsPanel3;
    private javax.swing.JPanel continentsPanel4;
    private javax.swing.JButton jButton1;
    public final javax.swing.JCheckBox landmarkCheckBox = new javax.swing.JCheckBox();
    public final javax.swing.JCheckBox landscapeCheckBox = new javax.swing.JCheckBox();
    public final javax.swing.JCheckBox landscapeFixCheckBox = new javax.swing.JCheckBox();
    public final javax.swing.JCheckBox livreryCheckBox = new javax.swing.JCheckBox();
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane mainScrollPane;
    private javax.swing.JPanel typePanel;
    // End of variables declaration//GEN-END:variables
}
