package msfsmodmanager.ui;

import msfsmodmanager.model.Continent;
import msfsmodmanager.model.ModType;
import msfsmodmanager.logic.ErrorHandler;

public class MainFrame extends javax.swing.JFrame {
    public final ContinentPanel eu = new ContinentPanel(Continent.EU);
    public final ContinentPanel uc = new ContinentPanel(Continent.UC);
    public final ContinentPanel ma = new ContinentPanel(Continent.MA);
    public final ContinentPanel sa = new ContinentPanel(Continent.SA);
    public final ContinentPanel as = new ContinentPanel(Continent.AS);
    public final ContinentPanel af = new ContinentPanel(Continent.AF);
    public final ContinentPanel oc = new ContinentPanel(Continent.OC);
    public final ContinentPanel aa = new ContinentPanel(Continent.AA);
    public final ContinentPanel of = new ContinentPanel(Continent.OF);
    
    public final AircraftPanel aircraftPanel = new AircraftPanel();
    
    private final MainFrameHandler handler = new MainFrameHandler(this);

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(applyButton);
        applyButton.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typePanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        rightButtonPanel = new javax.swing.JPanel();
        deactivateAllButton = new javax.swing.JButton();
        applyButton = new javax.swing.JButton();
        leftButtonPanel = new javax.swing.JPanel();
        contributeToModsDbButton = new javax.swing.JButton();
        mainScrollPane = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        continentsPanel1 = new javax.swing.JPanel();
        continentsPanel1.add(eu);
        continentsPanel2 = new javax.swing.JPanel();
        continentsPanel2.add(uc);
        continentsPanel2.add(ma);
        continentsPanel2.add(sa);
        continentsPanel3 = new javax.swing.JPanel();
        continentsPanel3.add(as);
        continentsPanel3.add(af);
        continentsPanel4 = new javax.swing.JPanel();
        continentsPanel4.add(oc);
        continentsPanel4.add(aa);
        continentsPanel4.add(of);
        continentsPanel4.add(aircraftPanel);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MSFS Mod Selector");

        airportCheckBox.setSelected(ModType.defaultSelection.contains(ModType.AIRPORT));
        airportCheckBox.setText(I18N.getString("ModType.AP"));
        typePanel.add(airportCheckBox);

        landmarkCheckBox.setSelected(ModType.defaultSelection.contains(ModType.LANDMARK));
        landmarkCheckBox.setText(I18N.getString("ModType.LM"));
        typePanel.add(landmarkCheckBox);

        cityCheckBox.setSelected(ModType.defaultSelection.contains(ModType.CITY));
        cityCheckBox.setText(I18N.getString("ModType.CT"));
        typePanel.add(cityCheckBox);

        landscapeCheckBox.setSelected(ModType.defaultSelection.contains(ModType.LANDSCAPE));
        landscapeCheckBox.setText(I18N.getString("ModType.LS"));
        typePanel.add(landscapeCheckBox);

        landscapeFixCheckBox.setSelected(ModType.defaultSelection.contains(ModType.LANDSCAPE_FIX));
        landscapeFixCheckBox.setText(I18N.getString("ModType.LF"));
        typePanel.add(landscapeFixCheckBox);

        livreryCheckBox.setSelected(ModType.defaultSelection.contains(ModType.LIVRERY));
        livreryCheckBox.setText(I18N.getString("ModType.AL"));
        typePanel.add(livreryCheckBox);

        aircraftModelCheckBox.setSelected(ModType.defaultSelection.contains(ModType.AIRCRAFT_MODEL));
        aircraftModelCheckBox.setText(I18N.getString("ModType.AM"));
        typePanel.add(aircraftModelCheckBox);

        otherCheckBox.setSelected(ModType.defaultSelection.contains(ModType.OTHER));
        otherCheckBox.setText(I18N.getString("ModType.OT"));
        typePanel.add(otherCheckBox);

        getContentPane().add(typePanel, java.awt.BorderLayout.NORTH);

        buttonPanel.setLayout(new java.awt.BorderLayout());

        rightButtonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        deactivateAllButton.setText("Deactivate all");
        deactivateAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deactivateAllButtonActionPerformed(evt);
            }
        });
        rightButtonPanel.add(deactivateAllButton);

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });
        rightButtonPanel.add(applyButton);

        buttonPanel.add(rightButtonPanel, java.awt.BorderLayout.EAST);

        leftButtonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        contributeToModsDbButton.setText("Contribute to mods DB");
        contributeToModsDbButton.setToolTipText("Export the new mod definitions you have added in order to upload them to the central repository.");
        contributeToModsDbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contributeToModsDbButtonActionPerformed(evt);
            }
        });
        leftButtonPanel.add(contributeToModsDbButton);

        buttonPanel.add(leftButtonPanel, java.awt.BorderLayout.WEST);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        mainPanel.setLayout(new java.awt.GridLayout(1, 5));

        continentsPanel1.setLayout(new javax.swing.BoxLayout(continentsPanel1, javax.swing.BoxLayout.PAGE_AXIS));
        mainPanel.add(continentsPanel1);

        continentsPanel2.setLayout(new javax.swing.BoxLayout(continentsPanel2, javax.swing.BoxLayout.PAGE_AXIS));
        mainPanel.add(continentsPanel2);

        continentsPanel3.setLayout(new javax.swing.BoxLayout(continentsPanel3, javax.swing.BoxLayout.PAGE_AXIS));
        mainPanel.add(continentsPanel3);

        continentsPanel4.setLayout(new javax.swing.BoxLayout(continentsPanel4, javax.swing.BoxLayout.PAGE_AXIS));
        mainPanel.add(continentsPanel4);

        mainScrollPane.setViewportView(mainPanel);

        getContentPane().add(mainScrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        try {
            handler.apply();
        }
        catch (Exception ex) {
            ErrorHandler.handleGlobalError(ex);
        }
    }//GEN-LAST:event_applyButtonActionPerformed

    private void deactivateAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deactivateAllButtonActionPerformed
        try {
            handler.deactivateAll();
        }
        catch (Exception ex) {
            ErrorHandler.handleGlobalError(ex);
        }
    }//GEN-LAST:event_deactivateAllButtonActionPerformed

    private void contributeToModsDbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contributeToModsDbButtonActionPerformed
        try {
            handler.addUserDefinedModsToModsDb();
        }
        catch (Exception ex) {
            ErrorHandler.handleGlobalError(ex, false);
        }
    }//GEN-LAST:event_contributeToModsDbButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public final javax.swing.JCheckBox aircraftModelCheckBox = new javax.swing.JCheckBox();
    public final javax.swing.JCheckBox airportCheckBox = new javax.swing.JCheckBox();
    private javax.swing.JButton applyButton;
    private javax.swing.JPanel buttonPanel;
    public final javax.swing.JCheckBox cityCheckBox = new javax.swing.JCheckBox();
    private javax.swing.JPanel continentsPanel1;
    private javax.swing.JPanel continentsPanel2;
    private javax.swing.JPanel continentsPanel3;
    private javax.swing.JPanel continentsPanel4;
    private javax.swing.JButton contributeToModsDbButton;
    private javax.swing.JButton deactivateAllButton;
    public final javax.swing.JCheckBox landmarkCheckBox = new javax.swing.JCheckBox();
    public final javax.swing.JCheckBox landscapeCheckBox = new javax.swing.JCheckBox();
    public final javax.swing.JCheckBox landscapeFixCheckBox = new javax.swing.JCheckBox();
    private javax.swing.JPanel leftButtonPanel;
    public final javax.swing.JCheckBox livreryCheckBox = new javax.swing.JCheckBox();
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane mainScrollPane;
    public final javax.swing.JCheckBox otherCheckBox = new javax.swing.JCheckBox();
    private javax.swing.JPanel rightButtonPanel;
    private javax.swing.JPanel typePanel;
    // End of variables declaration//GEN-END:variables
}
