package msfsmodmanager.ui.main;

import java.util.ArrayList;
import java.util.List;

import msfsmodmanager.model.AircraftType;
import msfsmodmanager.ui.I18N;

public class AircraftPanel extends javax.swing.JPanel {

    /**
     * Creates new form AircraftPanel
     */
    public AircraftPanel() {
        initComponents();
    }
    
    public List<AircraftType> getSelection() {
        List<AircraftType> ret = new ArrayList<>();
        if (airlinerCheckBox.isSelected()) ret.add(AircraftType.AIRLINER);
        if (jetCheckBox.isSelected()) ret.add(AircraftType.JET);
        if (turbopropCheckBox.isSelected()) ret.add(AircraftType.TURBOPROP);
        if (propellerCheckBox.isSelected()) ret.add(AircraftType.PROPELLER);
        return ret;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder(I18N.getString("AircraftType")));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        airlinerCheckBox.setSelected(true);
        airlinerCheckBox.setText(I18N.getString("AircraftType.AL"));
        add(airlinerCheckBox);

        jetCheckBox.setSelected(true);
        jetCheckBox.setText(I18N.getString("AircraftType.JT"));
        add(jetCheckBox);

        turbopropCheckBox.setSelected(true);
        turbopropCheckBox.setText(I18N.getString("AircraftType.TP"));
        add(turbopropCheckBox);

        propellerCheckBox.setSelected(true);
        propellerCheckBox.setText(I18N.getString("AircraftType.PR"));
        add(propellerCheckBox);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public final javax.swing.JCheckBox airlinerCheckBox = new javax.swing.JCheckBox();
    public final javax.swing.JCheckBox jetCheckBox = new javax.swing.JCheckBox();
    public final javax.swing.JCheckBox propellerCheckBox = new javax.swing.JCheckBox();
    public final javax.swing.JCheckBox turbopropCheckBox = new javax.swing.JCheckBox();
    // End of variables declaration//GEN-END:variables
}
