package msfsmodmanager.ui.main;

import java.util.List;
import javax.swing.JComponent;
import javax.swing.JLabel;

public class CheckBoxTitledBorderPanel<T, C extends JComponent & SelectableComp> extends javax.swing.JPanel implements SelectableComp {
    private final String name;
    private final List<C> selectableComponents;
    
    public CheckBoxTitledBorderPanel(String name, String title, List<C> components) {
        setBorder(new CheckBoxTitledBorder(title, false));
        this.name = name;
        this.selectableComponents = components;
        initSelectableComponents();
        if (selectableComponents.isEmpty()) {
            add(new JLabel("                                   "));
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    public List<C> getSelectableComponents() {
        return selectableComponents;
    }
    
    private void initSelectableComponents() {
        for (C component : selectableComponents) {
            add(component);
        }
    }
    
    @Override
    public String getName() {
        return name;
    }
    
    @Override
    public boolean isSelected() {
        return getBorder().isSelected();
    }
    
    public CheckBoxTitledBorder getBorder() {
        return (CheckBoxTitledBorder) super.getBorder();
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
